language: node_js
sudo: required
node_js:
- lts/*
cache:
  directories:
  - node_modules
branches:
  only:
  - master
addons:
  ssh_known_hosts:
  - 47.105.40.207
before_install:
- openssl aes-256-cbc -K $encrypted_77f76d6cdcd2_key -iv $encrypted_77f76d6cdcd2_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- chmod u+x *.sh
script:
- sh ./deploy.sh
after_success:
- ssh -o StrictHostKeyChecking=no root@47.105.40.207 
  ' cd /data/www/
    && rm -rf ./frontend
    && git clone -b deploy git@github.com:Thawsoar/nuxtjs-blog.git 
    && mv nuxtjs-blog frontend 
    && cd frontend && yarn install
    && pm2 delete 'nuxt-blog'
    pm2 start npm --name "nuxt-blog" -- run start
  '
env:
  global:
  - GH_REF: github.com/Thawsoar/nuxtjs-blog.git
